services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecommerce_db'
      - 'POSTGRES_PASSWORD=admin_password'
      - 'POSTGRES_USER=admin_user'
    ports:
      - '5432:5432'
