spring:
  application:
    name: database-locking

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: admin_user
    password: admin_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true